CREATE TABLE MAQUINAS.CAUSAS_POTENCIAIS (
						NOME VARCHAR(80),
						CHAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
						DESCRICAO LONG VARCHAR, 
						CHAVE_MODO_FALHA INTEGER NOT NULL,
						PRIMARY KEY (chave),
						CONSTRAINT causas_potenciais_chave_modo_falha_fkey FOREIGN KEY (CHAVE_MODO_FALHA)
						REFERENCES MAQUINAS.MODO_FALHA(CHAVE) ON DELETE CASCADE
						);