

CREATE TABLE MAQUINAS.COMPONENTE(
nome LONG VARCHAR,
chave INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
chave_subsistema INTEGER NOT NULL,
funcao LONG VARCHAR,
CONSTRAINT componente_chave_subsistema_fkey FOREIGN KEY (chave_subsistema) REFERENCES maquinas.subsistema(chave)
);