CREATE TABLE MAQUINAS.MAQUINA (
					NOME LONG VARCHAR,
						DATA_INSERCAO DATE,
						CODIGO INTEGER NOT NULL, + 
						DESCRICAO LONG VARCHAR, + 
						CHAVE_USUARIO INTEGER NOT NULL, + 
						CHAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), + 
				       PRIMARY KEY (CHAVE), +
						CONSTRAINT USUARIO_FK + 
						FOREIGN KEY (CHAVE_USUARIO) + 
						REFERENCES sad4gm.usuario (chave))
					)