DROP TABLE MAQUINAS.MAQUINA;

CREATE TABLE MAQUINAS.MAQUINA (
		NOME LONG VARCHAR,
		DATA_INSERCAO DATE,
		CODIGO INTEGER NOT NULL,
		DESCRICAO LONG VARCHAR,
		CHAVE_USUARIO INTEGER NOT NULL,
		CONSTRAINT USUARIO_FK
		FOREIGN KEY (CHAVE_USUARIO)
		REFERENCES sad4gm.usuario (chave)
	);