CREATE TABLE MAQUINAS.EFEITO(
NOME LONG VARCHAR,
CHAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CHAVE_MODO_FALHA INTEGER NOT NULL,
PRIMARY KEY (chave),
CONSTRAINT efeitos_chave_modo_falha_fkey FOREIGN KEY (CHAVE_MODO_FALHA)
REFERENCES MAQUINAS.MODO_FALHA(CHAVE) ON DELETE CASCADE
);