CREATE TABLE MAQUINAS.ACAO_RECOMENDADA(
NOME LONG VARCHAR,
DESCRICAO LONGVARCHAR,
CHAVE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CHAVE_CAUSA_POTENCIAL INTEGER NOT NULL,
PRIMARY KEY (CHAVE),
CONSTRAINT ACAO_RECOMENDADA_CAUSA_POTENCIAL_FKEY FOREIGN KEY (CHAVE_CAUSA_POTENCIAL) 
REFERENCES MAQUINAS.CAUSAS_POTENCIAIS(CHAVE) ON DELETE CASCADE
);