INSERT INTO SAD4GM.USUARIO( NOME, CHAVE, ID, SENHA, AUDITOR, ATIVO, ADMIN ) VALUES ( 'Admin', 1, 'admin', 'ED68D4177DCE16705BCDA969276EF17343CAD2EB90EB58DE9627CAEE8EFCB2F9', 'Default', 1, 1 ); 

INSERT INTO MAQUINAS.MAQUINA( NOME, DATA_INSERCAO, CODIGO, DESCRICAO, CHAVE_USUARIO, CHAVE ) VALUES ( 'Sistema Transformador', '2018-12-01', 1, 'Sistema Transformador de Alta Potência', 1, 1 ); 

INSERT INTO MAQUINAS.SUBSISTEMA( NOME, CHAVE, CHAVE_MAQUINA ) VALUES ( 'Parte Ativa', 1, 1 ); 
INSERT INTO MAQUINAS.SUBSISTEMA( NOME, CHAVE, CHAVE_MAQUINA ) VALUES ( 'Relés', 2, 1 ); 
INSERT INTO MAQUINAS.SUBSISTEMA( NOME, CHAVE, CHAVE_MAQUINA ) VALUES ( 'Buchas e Comutadores', 3, 1 ); 
INSERT INTO MAQUINAS.SUBSISTEMA( NOME, CHAVE, CHAVE_MAQUINA ) VALUES ( 'Sistema de Resfriamento', 4, 1 ); 

INSERT INTO MAQUINAS.COMPONENTE( NOME, CHAVE, CHAVE_SUBSISTEMA, FUNCAO ) VALUES ( 'Núcleo', 1, 1, 'Função do Núcelo' ); 

